title: Oliver Daniels-Koch
name: Oliver Daniels-Koch

  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  oliveradk

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jeykll-feed

# dirs made visible
include: ["_pages"]

atom_feed:
  hide: true

defaults:
# _posts
- scope:
    path: ""
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
# _pages
- scope:
    path: ""
    type: pages
  values:
    layout: single
    author_profile: true

author:
  avatar   : "assets/images/prof.jpg"

